/**
 * Fetches every icon in `manifest.mjs`, in every weight, from the Phosphor
 * core repository (MIT) and writes the path data to
 * `src/design-system/icon-paths.js`. That generated file is committed: the
 * product makes no request for an icon at runtime and carries no icon package.
 *
 *   node scripts/icons/vendor.mjs
 *
 * Phosphor's SVGs are filled outlines on a 256×256 viewBox. Regular, bold and
 * fill are one path each; duotone is two, the first at opacity .2. The script
 * keeps exactly that: `[d]` or `[dBack, dFront]`.
 */
import { writeFile } from 'node:fs/promises';
import { ICONS, WEIGHTS } from './manifest.mjs';

const BASE = 'https://raw.githubusercontent.com/phosphor-icons/core/main/assets';

function fileFor(name, weight) {
  return weight === 'regular' ? `${name}.svg` : `${name}-${weight}.svg`;
}

async function fetchPaths(name, weight) {
  const url = `${BASE}/${weight}/${fileFor(name, weight)}`;
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${response.status} for ${url}`);
  const svg = await response.text();
  const paths = [...svg.matchAll(/<path\b([^>]*)\/?>/g)].map((match) => {
    const attrs = match[1];
    const d = /\bd="([^"]+)"/.exec(attrs)?.[1];
    const opacity = /\bopacity="([^"]+)"/.exec(attrs)?.[1];
    if (!d) throw new Error(`no d in ${url}`);
    return { d, opacity };
  });
  if (paths.length === 0) throw new Error(`no path in ${url}`);
  if (weight === 'duotone') {
    // Back layer first, front second — the order Phosphor writes them.
    const back = paths.filter((path) => path.opacity);
    const front = paths.filter((path) => !path.opacity);
    if (back.length !== 1 || front.length !== 1) {
      throw new Error(`unexpected duotone layering in ${url}: ${paths.length} paths`);
    }
    return [back[0].d, front[0].d];
  }
  if (paths.length !== 1) throw new Error(`expected one path in ${url}, got ${paths.length}`);
  return [paths[0].d];
}

const out = {};
const names = Object.keys(ICONS);
let done = 0;
for (const name of names) {
  const source = ICONS[name];
  out[name] = {};
  await Promise.all(
    WEIGHTS.map(async (weight) => {
      out[name][weight] = await fetchPaths(source, weight);
    }),
  );
  done += 1;
  process.stdout.write(`\r${done}/${names.length} ${name}        `);
}
process.stdout.write('\n');

const header = `/* Generated by \`node scripts/icons/vendor.mjs\` from Phosphor Icons (MIT,
 * https://github.com/phosphor-icons/core). Do not edit — edit
 * \`scripts/icons/manifest.mjs\` and run the script again.
 *
 * Shape: { name: { regular: [d], bold: [d], fill: [d], duotone: [back, front] } }
 * on a 256×256 viewBox, filled with currentColor.
 */
`;
const body = `export const ICON_PATHS = ${JSON.stringify(out)};\n`;
await writeFile(new URL('../../src/design-system/icon-paths.js', import.meta.url), header + body);
console.log(`wrote ${names.length} icons × ${WEIGHTS.length} weights`);
