/**
 * Vendors the Phosphor glyphs the board uses into `js/icons.js`, the same way
 * `scripts/icons/vendor.mjs` does for the product: path data only, four
 * weights, 256×256 viewBox, MIT (https://github.com/phosphor-icons/core).
 *
 * Reuses what the product already vendored (`src/design-system/icon-paths.js`)
 * and fetches the rest once. Run from the repo root:
 *
 *   node .scratch/brief-2026-08-21-staff-visual-direction/board/tools/build-icons.mjs
 *
 * The board never touches the product's manifest: a glyph this board needs and
 * the product does not is this board's business until a card asks for it.
 */
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, '../../../..');
const { ICONS } = await import(path.join(repo, 'scripts/icons/manifest.mjs').replace(/\\/g, '/').replace(/^([A-Za-z]):/, 'file:///$1:'));
const { ICON_PATHS } = await import(path.join(repo, 'src/design-system/icon-paths.js').replace(/\\/g, '/').replace(/^([A-Za-z]):/, 'file:///$1:'));

// Phosphor names the board needs. Our name == the Phosphor name here, on
// purpose: the board is a mock, not the product, and it should be obvious
// which glyph is which when a direction is chosen and the real manifest grows.
const NAMES = [
  // chrome
  'coffee', 'briefcase', 'users-three', 'strategy', 'student', 'chats-circle', 'chart-bar',
  'calendar-blank', 'sparkle', 'book-open', 'gear', 'sign-out', 'bell', 'magnifying-glass',
  'caret-down', 'caret-right', 'caret-up', 'dots-three', 'x', 'list', 'corners-out', 'corners-in',
  // task detail
  'phone', 'check-circle', 'arrow-up', 'arrow-down', 'minus', 'arrow-right', 'arrow-square-out',
  'play', 'chat-circle', 'chat-teardrop-text', 'chats', 'clock', 'info', 'waveform', 'smiley',
  'users', 'target', 'trend-up', 'trend-down', 'shield-check', 'envelope-simple', 'calendar-plus',
  'file-text', 'microphone', 'user', 'check', 'speaker-high', 'paper-plane-tilt', 'eye', 'lock',
  // morning brew
  'chart-line-up', 'clock-counter-clockwise', 'buildings', 'database', 'ruler', 'warning-circle',
  'calendar-x', 'eye-slash', 'question', 'hourglass', 'link', 'arrows-left-right', 'pause',
  'flag', 'prohibit', 'scales', 'path', 'stack', 'note-pencil', 'bookmark-simple',
];
const WEIGHTS = ['regular', 'bold', 'fill', 'duotone'];
const BASE = 'https://raw.githubusercontent.com/phosphor-icons/core/main/assets';

// product name → phosphor name, inverted, so a glyph the product already has
// is read from its file rather than fetched again.
const byPhosphor = Object.fromEntries(Object.entries(ICONS).map(([ours, ph]) => [ph, ours]));

function fileFor(name, weight) {
  return weight === 'regular' ? `${name}.svg` : `${name}-${weight}.svg`;
}

async function fetchPaths(name, weight) {
  const url = `${BASE}/${weight}/${fileFor(name, weight)}`;
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${response.status} for ${url}`);
  const svg = await response.text();
  const paths = [...svg.matchAll(/<path\b([^>]*)\/?>/g)].map((match) => {
    const attrs = match[1];
    const d = /\bd="([^"]+)"/.exec(attrs)?.[1];
    const opacity = /\bopacity="([^"]+)"/.exec(attrs)?.[1];
    if (!d) throw new Error(`no d in ${url}`);
    return { d, opacity };
  });
  if (paths.length === 0) throw new Error(`no path in ${url}`);
  if (weight === 'duotone') {
    const back = paths.filter((p) => p.opacity);
    const front = paths.filter((p) => !p.opacity);
    if (back.length !== 1 || front.length !== 1) {
      throw new Error(`unexpected duotone layering in ${url}: ${paths.length} paths`);
    }
    return [back[0].d, front[0].d];
  }
  // A glyph drawn as several subpaths (stack-fill) is one path to us.
  return [paths.map((p) => p.d).join(' ')];
}

const out = {};
let reused = 0;
let fetched = 0;
for (const name of NAMES) {
  const ours = byPhosphor[name];
  if (ours && ICON_PATHS[ours]) {
    out[name] = ICON_PATHS[ours];
    reused += 1;
    continue;
  }
  out[name] = {};
  await Promise.all(
    WEIGHTS.map(async (weight) => {
      out[name][weight] = await fetchPaths(name, weight);
    }),
  );
  fetched += 1;
  process.stdout.write(`\r${reused + fetched}/${NAMES.length} ${name}        `);
}
process.stdout.write('\n');

const banner = `/* Generated by tools/build-icons.mjs from Phosphor Icons (MIT,
 * https://github.com/phosphor-icons/core). ${reused} glyphs read from the
 * product's own icon-paths.js, ${fetched} fetched. Do not edit.
 *
 * Shape: { name: { regular: [d], bold: [d], fill: [d], duotone: [back, front] } }
 * on a 256×256 viewBox, filled with currentColor.
 */
`;
const target = path.join(here, '..', 'js', 'icons.js');
await writeFile(target, `${banner}window.PHOSPHOR = ${JSON.stringify(out)};\n`);
console.log(`wrote ${path.relative(repo, target)} — ${Object.keys(out).length} icons (${reused} reused, ${fetched} fetched)`);
